### ISSUE TITLE
urlsafe_base64 always ends in 09

### ISSUE THREAD

**Issue by davidmann4** [patricksrobertson/secure_random.ex#11]
Hi, I just noticed that urlsafe_base64 always ends in 09

![image](https://user-images.githubusercontent.com/1736570/48049948-ae4b7d80-e1a0-11e8-99de-ce6653c3a810.png)

**Comment by QMalcolm** [comment]
I believe this expected, and does not compromise security. The "09" is simply "==" (which is padding) being encoded.

The full definition of `SecureRandom.urlsafe_base64` can be looked at as `:crypto.strong_rand_bytes(16) |> Base.Encode64(case: :lower) |> Base.url_encode64(case: :lower, padding: true)`

The part `:crop.strong_rand_bytes(16)` generates a bitstring of 16 bytes. The `Base.Encode64(case: :lower) without padding creates a 22 character string, however, the default behavior of `Base.Encode64` adds padding (in the form of "=" characters) to this to get it to 24 characters. So when we encode this encoded string to be url safe, the "==" is deterministic and manifests dependent on the length of the string. For strings with lengths that are multiples of three, the "==" final characters become encoded as 09.

**Comment by schrockwell** [comment]
Why is there an extra encoding step for `urlsafe_base64`? It makes the generated string longer than is necessary without adding entropy. Is there a reason it's not, more simply, `:crypto.strong_rand_bytes(16) |> Base.url_encode64(case: :lower, padding: true)`?
